version: '3'
services:

  web:
    container_name: web
    image: trs:0.1.0
    build: .
    command: npm run prod
    restart: always
    environment:
      NODE_ENV: production
      TYPEORM_ENTITIES: "dist/entity/**/*.js"
      TYPEORM_MIGRATIONS: "dist/migration/**/*.js"
      TYPEORM_SUBSCRIBERS: "dist/subscriber/**/*.js"
    ports:
      - 3001:3001
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: "postgres:9.6.1"
    restart: always
    volumes:
      - my_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

volumes:
  my_data:
    external: true
